// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLCjQLd6CkYbFeZbmcpBVsUIYp_rzs0o',
    appId: '1:177164603745:web:0983a29d415e1dd1953520',
    messagingSenderId: '177164603745',
    projectId: 'wishlister-3858f',
    authDomain: 'wishlister-3858f.firebaseapp.com',
    storageBucket: 'wishlister-3858f.firebasestorage.app',
    measurementId: 'G-NKYFJZFSQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4IQTVdj2OYGHgQvMUvReHOZQsVWbnEBI',
    appId: '1:177164603745:android:37c4f5d05c727276953520',
    messagingSenderId: '177164603745',
    projectId: 'wishlister-3858f',
    storageBucket: 'wishlister-3858f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFboDIM5q64PqMNWDnjxqPV1zx15MmszY',
    appId: '1:177164603745:ios:081017a6a0b1c14e953520',
    messagingSenderId: '177164603745',
    projectId: 'wishlister-3858f',
    storageBucket: 'wishlister-3858f.firebasestorage.app',
    iosBundleId: 'com.example.wishlister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFboDIM5q64PqMNWDnjxqPV1zx15MmszY',
    appId: '1:177164603745:ios:081017a6a0b1c14e953520',
    messagingSenderId: '177164603745',
    projectId: 'wishlister-3858f',
    storageBucket: 'wishlister-3858f.firebasestorage.app',
    iosBundleId: 'com.example.wishlister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjLCjQLd6CkYbFeZbmcpBVsUIYp_rzs0o',
    appId: '1:177164603745:web:7c939b47fb38f9ad953520',
    messagingSenderId: '177164603745',
    projectId: 'wishlister-3858f',
    authDomain: 'wishlister-3858f.firebaseapp.com',
    storageBucket: 'wishlister-3858f.firebasestorage.app',
    measurementId: 'G-DPK17KM71Y',
  );
}
